### PR TITLE
Check connected clients in right way

### LINKED ISSUE #9: Observer can not play if last player quit room
Say we have two guys in room, one guy is observer while another is player.

In this case, if the unique player quit, the room will be deleted, that said if the observer wants to play, he/she can do nothing.

~~We should also store observer into redis with indicator says that oh this is observer.~~ --> Do not store observer into redis according to [here](https://github.com/IFS49F/poker-server/pull/10#discussion_r132612728).

### PR DESCRIPTION
**Pull request by just4fun**
This PR will resolve #9 .

The doc for socket.io sucks, I did not find any place mentioned the API I need, just found the answer on [stackoverflow](https://stackoverflow.com/a/35527764/2798001).

## Note

- What's the difference between `io.sockets.adapter.rooms[room].length` and `Object.keys(io.sockets.connected).length`?

> `io.sockets.adapter.rooms[room].length`: All connected clients in specific room
> `Object.keys(io.sockets.connected).length`: All connected clients

- Why I didn't check connected clients via `io.sockets.adapter.rooms[room].length === 0` but using `!io.sockets.adapter.rooms[room]`

> If there are no any connections in specific room, `io.sockets.adapter.rooms[room]` will be `undefined`.

### CODE REVIEW

**Comment by just4fun** [comment]
My wife is still working overtime, so I created this PR in a cafe 😅 .

**Comment by hyjk2000** [comment]
That's really a good find, good job Zoro!

What troubles me though is how obscure the code is and, the solution depends on the version of socket.io and the room adapter we're using (See this [answer](https://stackoverflow.com/a/24425207)). As long as this is not clearly defined as an property in socket.io, it's not a _stable_ solution.

In this case, assume the value of `io.socket.adapter.rooms[room]` is always `undefined` after a socket.io upgrade, that'll be a serious problem because rooms are removed when anyone leaves.

I suggest to wrap the logic in a method or add some comments to explain the situation.

**Review by hyjk2000 — COMMENTED** [review]
Generally I like this change. Just some concerns I want to be clarified in code or comments.

**Review by hyjk2000 — APPROVED** [review]

**Pull request merged**
